### PR TITLE
Add metalsmith.json support

### PR DESCRIPTION
**Pull request by msvbg**
My first PR ever, be nice ;)

### CODE REVIEW

**Comment by constantx** [comment]
awesome, I was wondering about this :)

**Comment by thehydroimpulse** [comment]
@msvbg Sorry, I didn't see this notification. I've got hundreds a day, so it's hard to keep up. I'll take a look at this, thanks.

**Comment by thehydroimpulse** [comment]
Thanks for the PR

**Comment by msvbg** [comment]
Cool, thanks yourself! :)

**Pull request merged**
